name: locking
version: 0.0.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: The "locking" prevents the simultaneous execution of the "locked" code in the different zones.
homepage: https://github.com/mezoni/locking
